"""checkouts

Revision ID: 315f3fb09c0f
Revises: 3b99d3d5fdc4
Create Date: 2026-09-07 00:23:32.546088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '315f3fb09c0f'
down_revision = '3b99d3d5fdc4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checkouts',
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('holder_name', sa.String(length=120), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('from_location_id', sa.UUID(), nullable=True),
    sa.Column('checked_out_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('due_back_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('returned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('note', sa.String(length=300), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint('char_length(holder_name) BETWEEN 1 AND 120', name='ck_checkouts_holder_length'),
    sa.CheckConstraint('quantity BETWEEN 1 AND 1000000', name='ck_checkouts_quantity'),
    sa.CheckConstraint('returned_at IS NULL OR returned_at >= checked_out_at', name='ck_checkouts_return_after_issue'),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['from_location_id'], ['locations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('checkouts', schema=None) as batch_op:
        batch_op.create_index('ix_checkouts_item_open', ['item_id', 'returned_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checkouts', schema=None) as batch_op:
        batch_op.drop_index('ix_checkouts_item_open')

    op.drop_table('checkouts')
    # ### end Alembic commands ###
