"""tamper-evident audit chain

Adds the hash chain to audit_log, denormalises the actor, drops the foreign key
that would require UPDATE on an append-only table, and revokes UPDATE/DELETE
from the application role.

Written by hand rather than autogenerated: the chain has to be backfilled over
existing rows in the same order the application would have produced it, and
grants are not something Alembic models.

Revision ID: a1c4e7b90d21
Revises: 315f3fb09c0f
"""
import hashlib
import os
from types import SimpleNamespace

import sqlalchemy as sa
from alembic import op

revision = "a1c4e7b90d21"
down_revision = "315f3fb09c0f"
branch_labels = None
depends_on = None

GENESIS_HASH = "0" * 64

#: Must match AuditLog.canonical() / compute_hash() in app/doom/models.py.
#: Duplicated deliberately: a migration has to keep working after the model
#: moves on, so it pins the format as it was at this revision.
_UNIT = "\x1f"
_RECORD = "\x1e"


def _canonical(row) -> str:
    return _UNIT.join([
        str(row.seq),
        row.created_at.isoformat() if row.created_at else "",
        str(row.actor_user_id or ""),
        row.actor_username or "",
        row.action or "",
        row.object_type or "",
        row.object_id or "",
        row.detail or "",
        row.ip or "",
    ])


def _row_hash(prev_hash: str, row) -> str:
    return hashlib.sha256(
        f"{prev_hash}{_RECORD}{_canonical(row)}".encode("utf-8")
    ).hexdigest()


def upgrade():
    bind = op.get_bind()

    # --- 1. denormalise the actor -------------------------------------------
    # The audit trail must outlive the accounts it describes, and the ON DELETE
    # SET NULL cascade below would be an UPDATE on a table the application is
    # about to lose UPDATE on.
    op.add_column("audit_log", sa.Column("actor_username", sa.String(32)))
    op.execute(
        """
        UPDATE audit_log a
           SET actor_username = u.username
          FROM users u
         WHERE a.actor_user_id = u.id
        """
    )

    # Drop the FK by discovered name — it differs between environments.
    fk = bind.execute(sa.text(
        """
        SELECT conname FROM pg_constraint
         WHERE conrelid = 'audit_log'::regclass AND contype = 'f'
        """
    )).scalars().all()
    for name in fk:
        op.execute(f'ALTER TABLE audit_log DROP CONSTRAINT "{name}"')

    # --- 2. chain columns ----------------------------------------------------
    op.add_column("audit_log", sa.Column("seq", sa.BigInteger()))
    op.add_column("audit_log", sa.Column("prev_hash", sa.String(64)))
    op.add_column("audit_log", sa.Column("row_hash", sa.String(64)))

    # --- 3. backfill in creation order --------------------------------------
    # Existing rows predate the chain, so they are linked now. This does not
    # prove they were never altered before today — it establishes a baseline
    # from which alterations become detectable.
    rows = bind.execute(sa.text(
        """
        SELECT id, created_at, actor_user_id, actor_username, action,
               object_type, object_id, detail, ip
          FROM audit_log
         ORDER BY created_at, id
        """
    )).all()

    prev = GENESIS_HASH
    for index, row in enumerate(rows, start=1):
        shim = SimpleNamespace(**dict(row._mapping), seq=index)
        digest = _row_hash(prev, shim)
        bind.execute(
            sa.text(
                "UPDATE audit_log SET seq = :seq, prev_hash = :prev, "
                "row_hash = :hash WHERE id = :id"
            ).bindparams(seq=index, prev=prev, hash=digest, id=row.id)
        )
        prev = digest

    op.alter_column("audit_log", "seq", nullable=False)
    op.alter_column("audit_log", "prev_hash", nullable=False)
    op.alter_column("audit_log", "row_hash", nullable=False)
    op.create_unique_constraint("uq_audit_log_seq", "audit_log", ["seq"])
    op.create_index("ix_audit_seq", "audit_log", ["seq"])

    # --- 4. append-only for the application role ----------------------------
    # The load-bearing control (T-45). After this, a complete SQL injection
    # through the application can add to history but never rewrite it.
    app_user = os.environ.get("APP_DB_USER", "doom_app")
    op.execute(f'REVOKE UPDATE, DELETE ON audit_log FROM "{app_user}"')
    op.execute(
        f'ALTER DEFAULT PRIVILEGES IN SCHEMA public '
        f'GRANT SELECT, INSERT ON TABLES TO "{app_user}"'
    )


def downgrade():
    app_user = os.environ.get("APP_DB_USER", "doom_app")
    op.execute(f'GRANT UPDATE, DELETE ON audit_log TO "{app_user}"')

    op.drop_index("ix_audit_seq", table_name="audit_log")
    op.drop_constraint("uq_audit_log_seq", "audit_log", type_="unique")
    op.drop_column("audit_log", "row_hash")
    op.drop_column("audit_log", "prev_hash")
    op.drop_column("audit_log", "seq")
    op.drop_column("audit_log", "actor_username")

    op.create_foreign_key(
        "audit_log_actor_user_id_fkey", "audit_log", "users",
        ["actor_user_id"], ["id"], ondelete="SET NULL",
    )
