"""initial schema

Revision ID: e9da0d0e6211
Revises: 
Create Date: 2026-09-06 18:27:05.834438

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e9da0d0e6211'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('username', postgresql.CITEXT(), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('session_version', sa.Integer(), nullable=False),
    sa.Column('failed_login_count', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('char_length(username) BETWEEN 3 AND 32', name='ck_users_username_length'),
    sa.CheckConstraint('failed_login_count >= 0', name='ck_users_failed_count'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('audit_log',
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('object_type', sa.String(length=32), nullable=True),
    sa.Column('object_id', sa.String(length=64), nullable=True),
    sa.Column('detail', sa.String(length=500), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index('ix_audit_action_created', ['action', 'created_at'], unique=False)
        batch_op.create_index('ix_audit_actor_created', ['actor_user_id', 'created_at'], unique=False)

    op.create_table('locations',
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('kind', sa.Enum('warehouse', 'zone', 'rack', 'shelf', 'bin', 'tote', name='location_kind'), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('depth', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('visibility', sa.Enum('private', 'shared', name='visibility_level'), nullable=False),
    sa.Column('share_token', sa.String(length=64), nullable=True),
    sa.Column('short_code', sa.String(length=16), nullable=True),
    sa.Column('share_pin_hash', sa.String(length=255), nullable=True),
    sa.CheckConstraint('char_length(name) BETWEEN 1 AND 120', name='ck_locations_name_length'),
    sa.CheckConstraint('depth BETWEEN 0 AND 12', name='ck_locations_depth'),
    sa.CheckConstraint('id <> parent_id', name='ck_locations_not_self_parent'),
    sa.CheckConstraint('notes IS NULL OR char_length(notes) <= 4000', name='ck_locations_notes_length'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['locations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('share_token'),
    sa.UniqueConstraint('short_code')
    )
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.create_index('ix_locations_owner_parent', ['owner_id', 'parent_id'], unique=False)

    op.create_table('items',
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('location_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('visibility', sa.Enum('private', 'shared', name='visibility_level'), nullable=False),
    sa.Column('share_token', sa.String(length=64), nullable=True),
    sa.Column('short_code', sa.String(length=16), nullable=True),
    sa.Column('share_pin_hash', sa.String(length=255), nullable=True),
    sa.CheckConstraint('char_length(name) BETWEEN 1 AND 120', name='ck_items_name_length'),
    sa.CheckConstraint('description IS NULL OR char_length(description) <= 4000', name='ck_items_description_length'),
    sa.CheckConstraint('quantity BETWEEN 0 AND 1000000', name='ck_items_quantity_range'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('share_token'),
    sa.UniqueConstraint('short_code')
    )
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.create_index('ix_items_owner_location', ['owner_id', 'location_id'], unique=False)

    op.create_table('attachments',
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=True),
    sa.Column('location_id', sa.UUID(), nullable=True),
    sa.Column('kind', sa.Enum('photo', 'document', name='attachment_kind'), nullable=False),
    sa.Column('stored_name', sa.String(length=80), nullable=False),
    sa.Column('thumbnail_name', sa.String(length=80), nullable=True),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=80), nullable=False),
    sa.Column('byte_size', sa.BigInteger(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint('byte_size > 0 AND byte_size <= 10485760', name='ck_attachments_size'),
    sa.CheckConstraint('num_nonnulls(item_id, location_id) = 1', name='ck_attachments_one_target'),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stored_name')
    )
    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.create_index('ix_attachments_item', ['item_id'], unique=False)
        batch_op.create_index('ix_attachments_location', ['location_id'], unique=False)

    op.create_table('doc_links',
    sa.Column('item_id', sa.UUID(), nullable=True),
    sa.Column('location_id', sa.UUID(), nullable=True),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('url', sa.String(length=2000), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint("url LIKE 'http://%%' OR url LIKE 'https://%%'", name='ck_doc_links_url_scheme'),
    sa.CheckConstraint('num_nonnulls(item_id, location_id) = 1', name='ck_doc_links_one_target'),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('movements',
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('from_location_id', sa.UUID(), nullable=True),
    sa.Column('to_location_id', sa.UUID(), nullable=True),
    sa.Column('delta_qty', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['from_location_id'], ['locations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_location_id'], ['locations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('movements', schema=None) as batch_op:
        batch_op.create_index('ix_movements_item_created', ['item_id', 'created_at'], unique=False)

    op.create_table('nfc_tags',
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=True),
    sa.Column('location_id', sa.UUID(), nullable=True),
    sa.Column('tag_uid', sa.String(length=64), nullable=False),
    sa.Column('written_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint('num_nonnulls(item_id, location_id) = 1', name='ck_nfc_tags_one_target'),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'tag_uid', name='uq_nfc_tags_owner_uid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nfc_tags')
    with op.batch_alter_table('movements', schema=None) as batch_op:
        batch_op.drop_index('ix_movements_item_created')

    op.drop_table('movements')
    op.drop_table('doc_links')
    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.drop_index('ix_attachments_location')
        batch_op.drop_index('ix_attachments_item')

    op.drop_table('attachments')
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_index('ix_items_owner_location')

    op.drop_table('items')
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.drop_index('ix_locations_owner_parent')

    op.drop_table('locations')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_actor_created')
        batch_op.drop_index('ix_audit_action_created')

    op.drop_table('audit_log')
    op.drop_table('users')
    # ### end Alembic commands ###
